<a href="https://colab.research.google.com/github/hemilygomes/dojopython/blob/main/Datafolia2022_Concentra_mas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Concentra mas Numpy

In [32]:
import numpy as np

###Criando um vetor com os seguintes valores [1,2,3,4,5], chame-o de vetA

In [33]:
vetA = np.array([1,2,3,4,5])

###Exiba os 3 primeiros elementos

In [34]:
vetA[0:3]

array([1, 2, 3])

###Exiba todos os valores após o quinto elemento


In [35]:
vetA[5:]

array([], dtype=int64)

###Exiba os 3 últimos elementos

In [36]:
vetA[-3:]

array([3, 4, 5])

###Exiba os valores de vetA entre o 5 elemento até o penúltimo elemento

In [37]:
vetor=np.array([0,1,2,3,4,5,6,7,8,9,10])

In [38]:
vetor[5:-1]

array([5, 6, 7, 8, 9])

In [39]:
vetA[5:-1]

array([], dtype=int64)

###Crie uma matriz 5x5

In [40]:
matriz=np.arange(25).reshape(5,5)

###Exiba a matriz inteira

In [41]:
matriz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

###Exiba todos os elementos da coluna 3

In [49]:
matriz[0:5,2:3]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

###Exiba todos os elementos da linha 2

In [50]:
matriz[1]

array([5, 6, 7, 8, 9])

###Exiba todos os elementos das 2 primeiras colunas

In [51]:
matriz[0:5,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

###Exiba todos os elementos das 2 primeiras linhas

In [52]:
matriz[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

###Exiba Apenas os elementos das 2 últimas linhas e das 4 últimas colunas

In [56]:
matriz[-2:,-4:]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

###Crie uma função que receba dois vetores e realize a soma de seus valores

In [64]:
def soma_vet(A,B):
  return A+B

In [65]:
A=np.array([1,2,3])
B=np.array([4,5,6])
A+B

array([5, 7, 9])

In [66]:
soma_vet(A,B)

array([5, 7, 9])

###Generalize a função acima para que ela receba uma string representando a operação a ser executada: '+' ou '-'

In [73]:
def oper_vet(A,B,operacao):
  if operacao == '+':
    return A+B
  elif operacao == '-':
    return A-B
  else:
    print('Operação Inválida')

In [75]:
oper_vet(A,B,'+')

array([5, 7, 9])

In [76]:
oper_vet(A,B,'-')

array([-3, -3, -3])

###Como calcular a média dos valores de uma matriz

In [77]:
matriz.mean()

12.0

###Calcule apenas a média das linhas

In [86]:
matriz[0].mean()

2.0

In [84]:
media_linha = []
for i in range(0,5):
  media = matriz[i].mean()
  media_linha.append(media)
  print(i, media_linha[i])

0 2.0
1 7.0
2 12.0
3 17.0
4 22.0


###Calcule apenas a média das colunas

In [89]:
matriz[0:,0:1].mean()

10.0

In [90]:
media_col = []
for i in range(0,5):
  media = matriz[0:,i:i+1].mean()
  media_col.append(media)
  print(i, media_col[i])

0 10.0
1 11.0
2 12.0
3 13.0
4 14.0
